### ISSUE TITLE
Please update to GnuCOBOL 3.0

### ISSUE THREAD

**Issue by GitMensch** [morecobol/docker-gnucobol#1]
The current version is from 2016, the much more stable 3.0RC1 can be found at https://alpha.gnu.org/gnu/gnucobol

Note: if there's no need to get it from amazon I think getting directly from gnu.org (or preferably a mirror) and ideally verifying the signature would be preferable.

**Comment by tjwebb** [comment]
resolved in https://github.com/morecobol/docker-gnucobol/pull/2
